config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "welcome#index"

  resources :users
  resources :sessions
  resources :profiles

  resources :articles do
    resources :comments
  end

  resources :friendships

  resources :articles do
    collection do
      get :search
    end
  end

  resources :messages

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
    length: { minimum: 5 }

  #searchable do
    #string :title
    #text :title
    #integer :user_id
    #string :description
    #text :description
  #end

  #def self.search(search)
    #if search
      #where('title LIKE ? or text LIKE ?', "%#{search}%", "%#{search}%")
    #else
      #all
    #end
  #end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :article, only: [:edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    #@search = Article.search do
    #fulltext params[:search]
    #order_by sort_column, sort_direction
    #paginate :page => params[:page], :per_page => 5
    #end
    #@articles = @search.results
    @articles = Article.order(sort_column + " " + sort_direction).page(params[:page]).per(5)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def article
    redirect_to articles_path unless @article = current_user.articles.find_by_id(params[:id])
  end

  def sort_column
    Article.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-horizontal">
    <div class="form-group">
      <div class="col-sm-3">
        <p>Title: <%= f.text_field :title, class: :"form-control" %></p>
        <p>Description: <%= f.text_area :description, class: :"form-control" %></p>
        <%= f.submit class: :"btn btn-info form-control" %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_search.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <%= text_field_tag :search, params[:search], class: :"form-control" %>
      <span class="input-group-btn">
        <%= submit_tag "Go!", name: :nil, class: :"btn btn-default" %>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
<div>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
</div>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path, class: :"btn btn-default" %>

app/views/articles/index.html.erb
<div class="navbar navbar-default navbar-right">
  <ul class="nav navbar-nav">
    <li><a href='#' data-div-id='article'>Articles</a></li>
    <li><a href='#' data-div-id='user'>Users</a></li>
    <li><a href='#' data-div-id='conversation'>Conversations</a></li>
    <li><a href='#' data-div-id='message'>New message</a></li>
    <li><a href='#' data-toggle="modal" data-target="#myModal">Modal form</a></li>
  </ul>
</div>

<div class='body'>
  <div id="article">
    <p>This is article page</p>
  </div>

  <div id="user">
    <p>This is user page</p>
  </div>

  <div id="conversation">
    <p>This is conversation page</p>
  </div>

  <div id="message">
    <p>This is message page</p>
  </div>

  <div id="result-string"></div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Write new string</h4>
      </div>
      <div class="modal-body">
        <input type="text" id="edit-string" class="form-control" placeholder="input text...">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" id="submit-string" class="btn btn-primary" data-dismiss="modal">Save on the page</button>
      </div>
    </div>
  </div>
</div>

<h1>Listing Articles</h1>
<%= form_tag articles_path, method: :get, id: 'articles_search' do %>
 <% render 'search' %>
<% end %>

<% if current_user %>
  <h3><%= link_to 'New article', new_article_path, class: :"label label-primary" %></h3>
<% end %>
<table>
  <tr>
    <th>Sort by author | </th>
    <th>Sort by title | </th>
    <th>Sort by description | </th>
  </tr>
</table>
<% @articles.each do |article| %>
  <div class="row">
    <div class="thumbnail">
      <div class="caption">
        <h3><%= article.title %></h3>
        <p><%= article.description %></p>
        <p><%= link_to 'Show', article_path(article), class: :"btn btn-info" %>
        <% if can_user(article) %>
          <%= link_to 'Edit', edit_article_path(article), class: :"btn btn-default" %>
          <%= link_to 'Destroy', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}, class: :"btn btn-danger" %>
        <% end %>
        <p>Written by <%= link_to article.user.email, profile_path(article.user_id), method: :get %></p>
        <p>Comments count <span class="badge"><%= article.comments.count %></span></p>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path, class: :"btn btn-default" %>

app/views/articles/show.html.erb
<div class="panel panel-default">
  <table class="table">
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Description</th>
      <th>Comments_count</th>
      <th colspan="3"></th>
    </tr>
    <tr>
      <td><%= @article.user.email %></td>
      <td><%= @article.title %></td>
      <td><%= @article.description %></td>
      <td><%= @article.comments.count %></td>
    </tr>
  </table>
</div>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>
<div class="btn-group">
  <%= link_to 'Edit Article', edit_article_path(@article), class: :"btn btn-info"%>
  <%= link_to 'Back to Articles', articles_path, class: :"btn btn-default" %>
</div>