config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "welcome#index"

  resources :users
  resources :sessions
  resources :profiles

  resources :articles do
    resources :comments
  end

  resources :friendships

  resources :articles do
    collection do
      get :search
    end
  end

  resources :messages

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate
  helper_method :mailbox, :conversation

  def index
    @conversations ||= current_user.mailbox.inbox.all
  end

  def show
    conversation = current_user.mailbox.conversations.find_by_id(params[:id])
    @messages = conversation.messages
  end

  def reply
    current_user.reply_to_conversation(conversation, params[:message][:body])
    if (params[:message][:body] != "")
      @message = current_user.mailbox.conversations.find_by_id(params[:id]).messages.last
    end
  end

  def trashbin
    @trash = current_user.mailbox.trash.all
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to conversations_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :back
  end

  def empty_trash
    current_user.mailbox.empty_trash
    redirect_to conversations_path
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find_by_id(params[:id])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_message.html.erb
<% @messages.each do |message| %>
  <div class="row">
    <div class="col-sm-9">
      <strong><%= User.find(message.sender_id).email %></strong>
      <div class="row">
        <div class="col-xs-8 col-sm-6">
          <div class="col-md-8 col-md-offset-3"><%= message.body %></div>
        </div>
        <div class="col-xs-4 col-sm-6">
          <div class="col-md-4 col-md-offset-12"><%= message.created_at.strftime("%D %H:%M") %></div>
        </div>
      </div>
    </div>
  </div><br>
<% end %>

app/views/conversations/index.html.erb
<h3><%= link_to "See your Trash", trashbin_conversations_path, method: :get, class: :"label label-info" %></h3>
<ul>
  <% @conversations.each do |conversation| %>
    <div class="panel panel-info">
      <div class="panel-body">
        <%= link_to conversation.messages.last.body, conversation_path(conversation.id), method: :get %>
      </div>
      <div class="panel-footer">
        <%= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p") %>
      </div>
      <%= link_to "Move to Trash", trash_conversation_path(conversation.id), method: :post, class: :'btn btn-warning form-control' %>
    </div>
  <% end %>
</ul>

app/views/conversations/reply.js.erb
<% publish_to "/messages/new" do %>
  $("#chat").append('<div class="row"><div class="col-sm-9"><strong><%= User.find(@message.sender_id).email %></strong><div class="row"><div class="col-xs-8 col-sm-6"><div class="col-md-8 col-md-offset-3"><%= @message.body %></div></div><div class="col-xs-4 col-sm-6"><div class="col-md-4 col-md-offset-12"><%= @message.created_at.strftime("%D %H:%M") %></div></div></div></div></div><br>');
  $(".row .input-group .form-control").val("")
<% end %>

app/views/conversations/show.html.erb
<ul id="chat">
  <%= render 'message' %>
</ul><br><br><br>
<%= render 'messages/form' %>
<%= subscribe_to "/messages/new"  %>

app/views/conversations/trashbin.html.erb
<% @trash.each do |trash| %>
<%= trash.subject %> | <%= link_to "Untrash", untrash_conversation_path(trash.id), method: :post %><br>
<% end %>
<div class="btn-group" role="group">
  <%= link_to "Back to conversations", conversations_path, class: :"btn btn-default" %>
  <%= link_to "Empty Trash", empty_trash_conversations_path, method: :post, data: {confirm: 'Are you sure?'}, class: :"btn btn-danger" %>
</div>