config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "welcome#index"

  resources :users
  resources :sessions
  resources :profiles

  resources :articles do
    resources :comments
  end

  resources :friendships

  resources :articles do
    collection do
      get :search
    end
  end

  resources :messages

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @users = User.where.not(id: current_user || nil)
  end

  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to friendships_path
    else
      flash[:error] = "Unable to add friend."
      redirect_to friendships_path
    end
  end

  def destroy
    @friendship = current_user.friendships.find_by_friend_id(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to friendships_path
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<h1>List of possible friends</h1>
<% @users.each do |user| %>
  <ul class="list-group">
    <li class="list-group-item">
      <%= user.email %>
      <div class="btn-group" role="group">
        <% if friend_present(user.id) %>
          <%= link_to "Delete", friendship_path(user.id), method: :delete, class: :"btn btn-danger" %>
        <% else %>
          <%= link_to "Add Friend", friendships_path(friend_id: user.id), method: :post, class: :"btn btn-primary" %>
        <% end %>
        <%= link_to "Profile", profile_path(user.id), method: :get, class: :"btn btn-info" %>
      </div>
    </li>
  </ul>
<% end %>