config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "welcome#index"

  resources :users
  resources :sessions
  resources :profiles

  resources :articles do
    resources :comments
  end

  resources :friendships

  resources :articles do
    collection do
      get :search
    end
  end

  resources :messages

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
    length: { minimum: 5 }

  #searchable do
    #string :title
    #text :title
    #integer :user_id
    #string :description
    #text :description
  #end

  #def self.search(search)
    #if search
      #where('title LIKE ? or text LIKE ?', "%#{search}%", "%#{search}%")
    #else
      #all
    #end
  #end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  COUNTRIES = [['Ukraine', 'Ukraine'], ['Russian', 'Russian'], ['USA', 'USA'], ['Japan', 'Japan'], ['China', 'China'], ['Kazakhstan', 'Kazakhstan'], ['Poland', 'Poland'], ['Korea', 'Korea'], ['Canada', 'Canada'], ['Mexico', 'Mexico']]
  SEX = [['Man', 'Man'], ['Woman', 'Woman']]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles

  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :comments
  has_one :profile

  attr_accessor :password

  before_save :encrypt_password
  after_create :default_profile

  validates :password, :email, :password_confirmation, presence: true
  validates :password, confirmation: true
  validates :email, uniqueness: true

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  private

  def encrypt_password
    if self.password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(self.password, self.password_salt)
    end
  end

  def default_profile
    self.create_profile
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :article, only: [:edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    #@search = Article.search do
    #fulltext params[:search]
    #order_by sort_column, sort_direction
    #paginate :page => params[:page], :per_page => 5
    #end
    #@articles = @search.results
    @articles = Article.order(sort_column + " " + sort_direction).page(params[:page]).per(5)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def article
    redirect_to articles_path unless @article = current_user.articles.find_by_id(params[:id])
  end

  def sort_column
    Article.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Article.find(params[:article_id]).comments
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate

  def new
    @message = current_user.messages.new
  end

  def create
    users_ids = params[:users_ids].split(',').map(&:to_i).uniq
    users_ids.delete(current_user.id)
    key = users_ids.push(current_user.id).sort.join('-')
    conversation = mailbox.conversations.find_by_subject(key)
    recipients = User.where(id: users_ids)
    if conversation
      current_user.reply_to_conversation(conversation, params[:body])
    else
      current_user.send_message(recipients, params[:body], key)
    end
    redirect_to conversations_path
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find_by_id(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate
  before_filter :check_current_user, only: [:new, :create]

  def index
    users = User.where('email LIKE ?', "%#{params[:query]}%").select('email, id')
    render json: users
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
      flash[:error] = 'Error'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def can_user(object)
    current_user && object.user_id == current_user.id
  end

  def current_page(object)
    'active' if object == params[:controller]
  end

  def friend_present(object)
    current_user && current_user.friendships.map(&:friend_id).include?(object)
  end

  # def sortable(column, title = nil)
  #   title ||= column.titleize
  #   css_class = column == sort_column ? "current #{sort_direction}" : nil
  #   direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  #   link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  # end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_links.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Main", root_path, class: :"navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= current_page('articles') %>"><%= link_to "Articles", articles_path %></li>
        <li class="<%= current_page('friendships') %>"><%= link_to "Users", friendships_path %></li>
        <li class="<%= current_page('conversations') %>"><%= link_to "Conversations", conversations_path %></li>
        <li class="<%= current_page('messages') %>"><%= link_to "New message", new_message_path %></li>
      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <p class="navbar-text">Signed in as <%= current_user.email %> (ID -  <%= current_user.id %>)</p>
          <li class="<%= current_page('profiles') %>"><%= link_to "Profile", profiles_path %></li>
          <li><%= link_to "Log out", log_out_path %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <p class="navbar-text">You are not logged</p>
          <li class="<%= current_page('users') %>"><%= link_to "Sign up", sign_up_path %></li>
          <li class="<%= current_page('sessions') %>"><%= link_to "Log in", log_in_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    "application",  media: :all %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/links' %>
      <%= yield %>
    </div>
  </body>
</html>